### ISSUE TITLE
Run and annotate custom_lint if configured in project

### ISSUE THREAD

**Issue by kuhnroyal** [invertase/github-action-dart-analyzer#199]
It would be awesome if the action could detect and run https://github.com/invertase/dart_custom_lint and also annotate those warnings.
I can probably provide a PR but atm. the action kinda looks unmaintained.

FYI @rrousselGit

**Comment by rrousselGit** [comment]
It's something we've discussed internally.
It'd be great for sure. If you want to do it, go ahead

Although technically, this would be covered by a Dart SDK issue related to plugins. There's an issue with having `dart analyze` include analyzer_plugin lints. Which means this action would show custom_lint warnings without any extra work

**Comment by kuhnroyal** [comment]
> There's an issue with having `dart analyze` include analyzer_plugin lints.

Yea I have come across this, I don't see this happening in the near future.

**Comment by rrousselGit** [comment]
Right...
Hence if you want to do this, that's be great!
