### ISSUE TITLE
Discovery issue with v2 release

### ISSUE THREAD

**Issue by vbuberen** [invertase/github-action-dart-analyzer#217]
It seems that something is off with versioning for v2 release. 
A few days ago saw that Dependabot ignores the new v2 and thought that it is some Dependabot issue. However, after looking at logs I see that it wasn't able to find v2:
```
updater | 2023/05/29 21:59:35 INFO <job_670025379> Checking if invertase/github-action-dart-analyzer 1 needs updating
  proxy | 2023/05/29 21:59:35 [156] GET [https://github.com:443/invertase/github-action-dart-analyzer.git/info/refs?service=git-upload-pack](https://github.com/invertase/github-action-dart-analyzer.git/info/refs?service=git-upload-pack)
  proxy | 2023/05/29 21:59:35 [156] * authenticating git server request (host: github.com)
  proxy | 2023/05/29 21:59:35 [156] 200 [https://github.com:443/invertase/github-action-dart-analyzer.git/info/refs?service=git-upload-pack](https://github.com/invertase/github-action-dart-analyzer.git/info/refs?service=git-upload-pack)
updater | 2023/05/29 21:59:35 INFO <job_670025379> Latest version is 1
updater | 2023/05/29 21:59:35 INFO <job_670025379> No update needed for invertase/github-action-dart-analyzer 1
updater | 2023/05/29 21:59:35 INFO <job_670025379> Finished job processing
```

Also, today was updating the action to v2 in Plus Plugins and used the `default` syntax for version, like rest of actions use:
`invertase/github-action-dart-analyzer@v2` only to get this error on CI:
```
Error: Unable to resolve action `invertase/github-action-dart-analyzer@v2`, unable to find version `v2`
```

Only declaration with `invertase/github-action-dart-analyzer@v2.0.0` worked. 
I believe that it is confusing for users, especially since rest of actions use just `@v2`, `@v3` syntax. Maybe it is something to note for future releases.

**Comment by Salakar** [comment]
`v3` is now up, thanks
